import os
import sys
import re
from PIL import Image
from huggingface_hub import InferenceClient

# ১. কনফিগারেশন
HF_TOKEN = os.getenv("HF_TOKEN")
# কোডিংয়ের জন্য বর্তমানে সবচেয়ে নির্ভরযোগ্য ওপেন সোর্স মডেল
MODEL_ID = "Qwen/Qwen2.5-Coder-32B-Instruct" 

client = InferenceClient(model=MODEL_ID, token=HF_TOKEN)

def get_dominant_color(image_path):
    """ইমেজ থেকে ডমিন্যান্ট কালার বের করে থিমিংয়ের জন্য"""
    try:
        # অ্যাসেট ফোল্ডার চেক করা
        actual_path = image_path if os.path.exists(image_path) else f"assets/{os.path.basename(image_path)}"
        if not os.path.isfile(actual_path): 
            return '#1A1A1A'
            
        img = Image.open(actual_path).convert("RGB")
        img.thumbnail((50, 50))
        pixels = img.getcolors(img.size[0] * img.size[1])
        if not pixels: 
            return '#1A1A1A'
            
        most_common = sorted(pixels, key=lambda x: x[0], reverse=True)
        r, g, b = most_common[0][1][:3]
        return '#{:02x}{:02x}{:02x}'.format(r, g, b)
    except Exception: 
        return '#1A1A1A'

def clean_dart_code(raw_code):
    """কোড থেকে অপ্রয়োজনীয় টেক্সট এবং ব্যাকটিক পরিষ্কার করার মোক্ষম উপায় (Regex ব্যবহার করে)"""
    try:
        # শুধু ইমপোর্ট থেকে শেষ ব্র্যাকেট পর্যন্ত কোড ব্লকটি খুঁজে বের করা
        code_match = re.search(r'import.*void main\(.*\}', raw_code, re.DOTALL)
        if code_match:
            clean_code = code_match.group(0)
            return clean_code.strip()
        
        # যদি রেজেক্স ফেল করে, তবে ব্যাকটিক ম্যানুয়াল ক্লিনিং
        if "```dart" in raw_code:
            raw_code = raw_code.split("```dart")[1].split("```")[0]
        elif "```" in raw_code:
            raw_code = raw_code.split("```")[1].split("```")[0]
            
        return raw_code.strip()
    except Exception:
        return raw_code.strip()

def generate_ai_app(prompt, asset_name):
    hex_color = get_dominant_color(asset_name)
    
    # ইনস্ট্রাকশন সেট (Updated with Fixes)
    system_message = (
        f"You are an expert Flutter developer. Write ONLY a single, complete main.dart file. "
        f"Use Dark Mode. Use Primary Color: {hex_color}. Use assets/{asset_name} as a background image. "
        f"CRITICAL RULES:\n"
        f"1. NEVER use 'const' before a Tween if .animate() is called.\n"
        f"2. NEVER use a PageController as a parent for CurvedAnimation. Use an AnimationController instead.\n"
        f"3. Ensure all brackets are closed. NO explanations, NO Markdown text."
    )
    
    messages = [
        {"role": "system", "content": system_message},
        {"role": "user", "content": f"Task: {prompt}. Output only valid Dart code."}
    ]

    try:
        print(f"📡 Generating Flutter UI with {MODEL_ID}...")
        
        response = client.chat_completion(
            messages=messages,
            max_tokens=2500, 
            temperature=0.1  
        )
        
        raw_content = response.choices[0].message.content
        final_code = clean_dart_code(raw_content)
        
        # বেসিক সিনট্যাক্স চেক
        if "void main()" not in final_code:
            raise ValueError("Incomplete code generated by AI")
            
        return final_code

    except Exception as e:
        print(f"⚠️ Error encountered: {e}")
        # ফলব্যাক অ্যাপ
        return (
            "import 'package:flutter/material.dart';\n\n"
            "void main() => runApp(MaterialApp(theme: ThemeData.dark(), "
            "home: Scaffold(body: Center(child: Text('AI Generation Failed - Retry')))));"
        )

if __name__ == "__main__":
    # আর্গুমেন্ট হ্যান্ডলিং
    user_prompt = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1].strip() != "" else "Modern Dashboard UI"
    asset_file = os.path.basename(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2].strip() != "" else "background.png"
    
    print(f"🛠️ Starting Build Engine...")
    dart_code = generate_ai_app(user_prompt, asset_file)
    
    # ফাইল সেভ করা
    os.makedirs("lib", exist_ok=True)
    with open("lib/main.dart", "w", encoding="utf-8") as f:
        f.write(dart_code)
    
    print("✅ lib/main.dart has been updated successfully with AI fixes!")
    
