import os
import sys
from PIL import Image
from huggingface_hub import InferenceClient

# ১. কনফিগারেশন
HF_TOKEN = os.getenv("HF_TOKEN")
# কোডিংয়ের জন্য বর্তমানে সবচেয়ে নির্ভরযোগ্য ওপেন সোর্স মডেল
MODEL_ID = "Qwen/Qwen2.5-Coder-32B-Instruct" 

client = InferenceClient(model=MODEL_ID, token=HF_TOKEN)

def get_dominant_color(image_path):
    """ইমেজ থেকে ডমিন্যান্ট কালার বের করে থিমিংয়ের জন্য"""
    try:
        if not os.path.isfile(image_path): 
            return '#1A1A1A'
        img = Image.open(image_path).convert("RGB")
        img.thumbnail((50, 50))
        pixels = img.getcolors(img.size[0] * img.size[1])
        if not pixels: 
            return '#1A1A1A'
        # সবচেয়ে বেশি পিক্সেল আছে এমন কালারটি নেওয়া
        most_common = sorted(pixels, key=lambda x: x[0], reverse=True)
        r, g, b = most_common[0][1][:3]
        return '#{:02x}{:02x}{:02x}'.format(r, g, b)
    except Exception: 
        return '#1A1A1A'

def clean_dart_code(raw_code):
    """কোড থেকে অপ্রয়োজনীয় টেক্সট এবং ব্যাকটিক পরিষ্কার করার উন্নত লজিক"""
    # ১. যদি কোড ব্লকের ভেতরে থাকে (```dart ... ```)
    if "```" in raw_code:
        # ডার্ট ব্লকের অংশটি খুঁজে বের করা
        parts = raw_code.split("```")
        for part in parts:
            if "import 'package:flutter" in part:
                raw_code = part
                break
        # ল্যাঙ্গুয়েজ ট্যাগ রিমুভ করা
        if raw_code.startswith("dart"):
            raw_code = raw_code[4:]
        elif raw_code.startswith("flutter"):
            raw_code = raw_code[7:]

    # ২. কোডের বাইরের বাড়তি টেক্সট রিমুভ করা (Import এর আগের অংশ)
    if "import 'package:flutter" in raw_code:
        raw_code = raw_code[raw_code.find("import 'package:flutter"):]

    return raw_code.strip()

def generate_ai_app(prompt, asset_name):
    hex_color = get_dominant_color(f"assets/{asset_name}")
    
    # ইনস্ট্রাকশন সেট
    system_message = (
        f"You are an expert Flutter developer. Write ONLY a single, complete main.dart file. "
        f"Use Dark Mode. Use Primary Color: {hex_color}. Use assets/{asset_name} as a background image. "
        f"Ensure all brackets are closed. NO explanations, NO Markdown text."
    )
    
    messages = [
        {"role": "system", "content": system_message},
        {"role": "user", "content": f"Task: {prompt}. Output only valid Dart code."}
    ]

    try:
        print(f"📡 Generating Flutter UI with {MODEL_ID}...")
        
        response = client.chat_completion(
            messages=messages,
            max_tokens=2500, # কোড যেন মাঝপথে কেটে না যায়
            temperature=0.1  # নির্ভুল কোডের জন্য লো টেম্পারেচার
        )
        
        raw_content = response.choices[0].message.content
        final_code = clean_dart_code(raw_content)
        
        # বেসিক সিনট্যাক্স চেক
        if "void main()" not in final_code:
            raise ValueError("Incomplete code generated by AI")
            
        return final_code

    except Exception as e:
        print(f"⚠️ Error encountered: {e}")
        # ফলব্যাক অ্যাপ (যাতে বিল্ড প্রসেস পুরোপুরি বন্ধ না হয়ে যায়)
        return (
            "import 'package:flutter/material.dart';\n\n"
            "void main() => runApp(MaterialApp(theme: ThemeData.dark(), "
            "home: Scaffold(body: Center(child: Text('Build Issue - Please Re-run')))));"
        )

if __name__ == "__main__":
    # আর্গুমেন্ট হ্যান্ডলিং
    user_prompt = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1].strip() != "" else "Modern Dashboard UI"
    asset_file = os.path.basename(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2].strip() != "" else "background.png"
    
    print(f"🛠️ Starting Build Engine...")
    dart_code = generate_ai_app(user_prompt, asset_file)
    
    # ফাইল সেভ করা
    os.makedirs("lib", exist_ok=True)
    with open("lib/main.dart", "w", encoding="utf-8") as f:
        f.write(dart_code)
    
    print("✅ lib/main.dart has been updated successfully!")
    
